#!/usr/bin/env python3
"""gen_fixture.py — generate the DJ loader's level inputs from a committed
Archipelago-CC bounce_dj_worldgen preset.

Emits (into this directory):
  * region_<id>.js  — `window.__DJ_REGION = {...}` (the host-side configure()
    payload for the browser harness pages; regionId + params + checkedLocations)
  * FixtureData.as  — the SAME level as the loader's compact string, plus
    G|tick|items grant records, for EI-less runs (graphics-native headless).

The compact-string encoder here MUST stay in sync with the JS encoder in
dj_swf_bridge.js (encodeLevel) — same record format, same coordinate mapping,
same bottom-to-top index assignment. (~40 lines each; change both.)

Usage:
  python3 gen_fixture.py [--region region_4_4] [--grant-tick 300]
      [--rules ~/CC/Archipelago-CC/frontend/presets/bounce_dj_worldgen/
               AP_14089154938208861744/AP_14089154938208861744_rules.json]
"""
import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_RULES = Path.home() / (
    "CC/Archipelago-CC/frontend/presets/bounce_dj_worldgen/"
    "AP_14089154938208861744/AP_14089154938208861744_rules.json")

GATE_ITEM = {"blue": "Blue platforms", "brown": "Brown platforms"}
TYPE_CODE = {"green": "g", "brown": "b", "blue": "m"}

# DJ stage geometry (the SWF header RECT): with the stock 240px stage we
# render the center 240px strip of the 600px world; with a header-patched
# 600px stage (inject_tracer.py --stage-width 600) x maps 1:1. The level
# bottom always aligns with the stage bottom (screen y=400). Keep in sync
# with dj_swf_bridge.js.
STAGE_H = 400


def encode_level(level, side_portals, checked, stage_w):
    W, H = level["size"]["width"], level["size"]["height"]
    x_off = (W - stage_w) / 2
    y_off = H - STAGE_H

    def mx(x):
        v = x - x_off
        return int(v) if v == int(v) else v

    def my(y):
        v = y - y_off
        return int(v) if v == int(v) else v

    goals = {}
    for pk in level.get("pickups", []):
        goals[pk["on"]] = ("loc", pk["id"], "")
    portal_side = {pid: side for side, pid in (side_portals or {}).items()}
    for pt in level.get("portals", []):
        goals[pt["on"]] = ("exit", pt["id"], portal_side.get(pt["id"], ""))

    recs = [f"R|{level['id']}|{W}|{H}|{mx(W / 2)}|{my(H - 120)}"]
    # Bottom-to-top index assignment: the hero's catch loop scans a window of
    # block indices around lastblockhit, so indices must be local along the
    # climb. Stable sort keeps authored order for equal heights.
    plats = sorted(level["platforms"], key=lambda p: -p["y"])
    for i, p in enumerate(plats):
        kind, gid, side = goals.get(p["id"], ("", "", ""))
        gate = GATE_ITEM.get(p["type"], "")
        # Blue movers carry center-sweep bounds (P| FORMAT v2: two trailing
        # sweep fields, empty for static platforms).
        sweep = p.get("sweep")
        smin = mx(sweep["min"]) if sweep else ""
        smax = mx(sweep["max"]) if sweep else ""
        recs.append(f"P|{i}|{p['id']}|{TYPE_CODE.get(p['type'], 'g')}"
                    f"|{mx(p['x'])}|{my(p['y'])}|{gate}|{kind}|{gid}|{side}"
                    f"|{smin}|{smax}")
    if checked:
        recs.append("C|" + ",".join(checked))
    return ";".join(recs)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--region", default="region_4_4")
    ap.add_argument("--rules", type=Path, default=DEFAULT_RULES)
    ap.add_argument("--sidecar-player", default="1")
    ap.add_argument("--grant-tick", type=int, default=300,
                    help="fixture: tick at which the grant item arrives")
    ap.add_argument("--grant-item", default="Brown platforms",
                    help="fixture: item name granted at --grant-tick")
    ap.add_argument("--stage-width", type=int, default=240,
                    help="DJ stage width in px (600 for the header-patched wide build)")
    args = ap.parse_args()

    d = json.loads(args.rules.read_text())
    sidecar = d["preset_sidecars"][args.sidecar_player]
    region = sidecar[args.region]
    pp = region["playable_payload"]
    level = pp["params"]["bounceLevel"]
    side_portals = pp["params"].get("sidePortals", {})

    compact = encode_level(level, side_portals, checked=[], stage_w=args.stage_width)

    # Browser harness payloads: ALL regions, keyed by id, each with params +
    # the exits table (side -> targetRegion) so the mock host can follow
    # portal fires across region swaps like the real host bridge.
    regions = {rid: {"regionId": rid, "params": r["playable_payload"]["params"],
                     "exits": r["playable_payload"].get("exits", [])}
               for rid, r in sidecar.items()}
    regions_js = HERE / "regions.js"
    regions_js.write_text(
        "// GENERATED by gen_fixture.py from the committed preset — do not edit.\n"
        f"// Source: {args.rules}\n"
        "window.__DJ_REGIONS = " + json.dumps(regions, indent=1) + ";\n"
        "window.__DJ_START_REGION = window.__DJ_START_REGION || "
        + json.dumps(args.region) + ";\n")

    # EI-less fixture: same level + a deterministic item-grant schedule.
    fixture = f"{compact};G|0|;G|{args.grant_tick}|{args.grant_item}"
    (HERE / "FixtureData.as").write_text(
        "// GENERATED by gen_fixture.py — do not edit. See Loader.as for the\n"
        "// record format. Used when ExternalInterface is unavailable\n"
        "// (graphics-native headless), with G|tick|items grant scheduling.\n"
        "class FixtureData {\n"
        f"\tstatic var DATA:String = \"{fixture}\";\n"
        "}\n")

    print(f"wrote {regions_js.name} ({len(regions)} regions) and FixtureData.as")
    print(f"compact ({args.region}): {compact}")


if __name__ == "__main__":
    main()
