// GENERATED by gen_fixture.py from the committed preset — do not edit.
// Source: /home/robert/CC/Archipelago-CC/frontend/presets/bounce_dj_worldgen/AP_14089154938208861744/AP_14089154938208861744_rules.json
window.__DJ_REGION = {
 "regionId": "region_4_4",
 "params": {
  "bounceLevel": {
   "id": "region_4_4",
   "size": {
    "width": 600,
    "height": 970
   },
   "platforms": [
    {
     "id": "p0",
     "x": 300,
     "y": 870,
     "type": "green"
    },
    {
     "id": "p1",
     "x": 300,
     "y": 780,
     "type": "green"
    },
    {
     "id": "p2",
     "x": 300,
     "y": 690,
     "type": "green"
    },
    {
     "id": "p3",
     "x": 300,
     "y": 600,
     "type": "green"
    },
    {
     "id": "p4",
     "x": 300,
     "y": 510,
     "type": "green"
    },
    {
     "id": "p5",
     "x": 300,
     "y": 420,
     "type": "green"
    },
    {
     "id": "p6",
     "x": 300,
     "y": 330,
     "type": "green"
    },
    {
     "id": "p7",
     "x": 300,
     "y": 240,
     "type": "green"
    },
    {
     "id": "p8",
     "x": 300,
     "y": 150,
     "type": "green"
    },
    {
     "id": "p9",
     "x": 300,
     "y": 60,
     "type": "brown"
    },
    {
     "id": "p10",
     "x": 185,
     "y": 690,
     "type": "green"
    }
   ],
   "springs": [],
   "jetpacks": [],
   "pickups": [
    {
     "id": "loc_0",
     "x": 300,
     "y": 490,
     "on": "p4"
    }
   ],
   "portals": [
    {
     "id": "side_exit_W",
     "x": 300,
     "y": 40,
     "on": "p9",
     "target_region": null,
     "direction": "left"
    },
    {
     "id": "side_exit_N",
     "x": 185,
     "y": 670,
     "on": "p10",
     "target_region": null,
     "direction": "up"
    }
   ]
  },
  "sidePortals": {
   "W": "side_exit_W",
   "N": "side_exit_N"
  },
  "physics": {
   "profile": "dj",
   "constants": {
    "TICK_HZ": 20,
    "GRAVITY": 4,
    "MAX_FALL": 22,
    "BOUNCE_VY": -13,
    "SPRING_VY": -22,
    "JETPACK_VY": -36,
    "MOVE_ACCEL": 0.8,
    "AIR_DRAG": 0.92,
    "MAX_VX": 6,
    "PLATFORM_WIDTH": 60,
    "PLAYER_HALF_WIDTH": 23,
    "SPAWN_HEIGHT": 120,
    "FALL_MARGIN": 60,
    "AIR_CONTROL": "flat",
    "MOVE_FLAT": 10,
    "LANDING": "latched",
    "BOUNCE_IMPULSE": 32.29999959468838,
    "SPRING_IMPULSE": 68,
    "BROWN_IMPULSE": 32.29999959468838,
    "JETPACK_THRUST": 5,
    "JETPACK_TICKS": 100,
    "CATCH_BAND": 40.15,
    "WRAP": "edge",
    "PLATFORM_BEHAVIORS": {
     "blue": "moving",
     "brown": "breaking"
    },
    "BLUE_SPEED": 5,
    "POSITION_QUANTUM": 0.05
   }
  },
  "backExitSide": "N",
  "fallBehavior": "current"
 },
 "checkedLocations": []
};
