// GENERATED by gen_fixture.py from the committed preset — do not edit.
// Source: /home/robert/CC/Archipelago-CC/frontend/presets/bounce_dj_worldgen/AP_14089154938208861744/AP_14089154938208861744_rules.json
window.__DJ_REGIONS = {
 "region_3_3": {
  "regionId": "region_3_3",
  "params": {
   "bounceLevel": {
    "id": "region_3_3",
    "size": {
     "width": 600,
     "height": 880
    },
    "platforms": [
     {
      "id": "p0",
      "x": 300,
      "y": 780,
      "type": "green"
     },
     {
      "id": "p1",
      "x": 300,
      "y": 690,
      "type": "green"
     },
     {
      "id": "p2",
      "x": 300,
      "y": 600,
      "type": "green"
     },
     {
      "id": "p3",
      "x": 300,
      "y": 510,
      "type": "green"
     },
     {
      "id": "p4",
      "x": 300,
      "y": 420,
      "type": "green"
     },
     {
      "id": "p5",
      "x": 185,
      "y": 330,
      "type": "green"
     },
     {
      "id": "p6",
      "x": 185,
      "y": 240,
      "type": "green"
     },
     {
      "id": "p7",
      "x": 185,
      "y": 150,
      "type": "green"
     },
     {
      "id": "p8",
      "x": 185,
      "y": 60,
      "type": "green"
     },
     {
      "id": "p9",
      "x": 70,
      "y": 60,
      "type": "green"
     }
    ],
    "springs": [],
    "jetpacks": [],
    "pickups": [
     {
      "id": "loc_0",
      "x": 300,
      "y": 580,
      "on": "p2"
     }
    ],
    "portals": [
     {
      "id": "side_exit_E",
      "x": 70,
      "y": 40,
      "on": "p9",
      "target_region": null,
      "direction": "right"
     }
    ]
   },
   "sidePortals": {
    "E": "side_exit_E"
   },
   "physics": {
    "profile": "dj",
    "constants": {
     "TICK_HZ": 20,
     "GRAVITY": 4,
     "MAX_FALL": 22,
     "BOUNCE_VY": -13,
     "SPRING_VY": -22,
     "JETPACK_VY": -36,
     "MOVE_ACCEL": 0.8,
     "AIR_DRAG": 0.92,
     "MAX_VX": 6,
     "PLATFORM_WIDTH": 60,
     "PLAYER_HALF_WIDTH": 23,
     "SPAWN_HEIGHT": 120,
     "FALL_MARGIN": 60,
     "AIR_CONTROL": "flat",
     "MOVE_FLAT": 10,
     "LANDING": "latched",
     "BOUNCE_IMPULSE": 32.29999959468838,
     "SPRING_IMPULSE": 68,
     "BROWN_IMPULSE": 32.29999959468838,
     "JETPACK_THRUST": 5,
     "JETPACK_TICKS": 100,
     "CATCH_BAND": 40.15,
     "WRAP": "edge",
     "PLATFORM_BEHAVIORS": {
      "blue": "moving",
      "brown": "breaking"
     },
     "BLUE_SPEED": 5,
     "POSITION_QUANTUM": 0.05
    }
   }
  },
  "exits": [
   {
    "exit_id": "exit_E",
    "x": 7,
    "y": 3,
    "side": "E",
    "exitName": "exit_E",
    "targetRegion": "region_4_3",
    "isBackExit": false,
    "isTeleporter": false,
    "targetExitId": "region_3_3"
   }
  ]
 },
 "region_4_3": {
  "regionId": "region_4_3",
  "params": {
   "bounceLevel": {
    "id": "region_4_3",
    "size": {
     "width": 600,
     "height": 1420
    },
    "platforms": [
     {
      "id": "p0",
      "x": 300,
      "y": 1320,
      "type": "green"
     },
     {
      "id": "p1",
      "x": 300,
      "y": 1230,
      "type": "green"
     },
     {
      "id": "p2",
      "x": 300,
      "y": 1140,
      "type": "green"
     },
     {
      "id": "p3",
      "x": 300,
      "y": 1050,
      "type": "green"
     },
     {
      "id": "p4",
      "x": 300,
      "y": 960,
      "type": "green"
     },
     {
      "id": "p5",
      "x": 300,
      "y": 870,
      "type": "green"
     },
     {
      "id": "p6",
      "x": 300,
      "y": 780,
      "type": "green"
     },
     {
      "id": "p7",
      "x": 300,
      "y": 690,
      "type": "green"
     },
     {
      "id": "p8",
      "x": 300,
      "y": 600,
      "type": "green"
     },
     {
      "id": "p9",
      "x": 300,
      "y": 510,
      "type": "blue",
      "sweep": {
       "min": 15,
       "max": 585
      }
     },
     {
      "id": "p10",
      "x": 300,
      "y": 420,
      "type": "green"
     },
     {
      "id": "p11",
      "x": 300,
      "y": 330,
      "type": "green"
     },
     {
      "id": "p12",
      "x": 300,
      "y": 240,
      "type": "green"
     },
     {
      "id": "p13",
      "x": 300,
      "y": 150,
      "type": "green"
     },
     {
      "id": "p14",
      "x": 300,
      "y": 60,
      "type": "green"
     },
     {
      "id": "p15",
      "x": 185,
      "y": 1140,
      "type": "green"
     },
     {
      "id": "p16",
      "x": 185,
      "y": 1050,
      "type": "green"
     }
    ],
    "springs": [],
    "jetpacks": [],
    "pickups": [
     {
      "id": "loc_0",
      "x": 300,
      "y": 850,
      "on": "p5"
     },
     {
      "id": "loc_1",
      "x": 300,
      "y": 760,
      "on": "p6"
     }
    ],
    "portals": [
     {
      "id": "side_exit_N",
      "x": 300,
      "y": 40,
      "on": "p14",
      "target_region": null,
      "direction": "up"
     },
     {
      "id": "side_exit_S",
      "x": 185,
      "y": 1120,
      "on": "p15",
      "target_region": null,
      "direction": "down"
     },
     {
      "id": "side_exit_W",
      "x": 185,
      "y": 1030,
      "on": "p16",
      "target_region": null,
      "direction": "left"
     }
    ]
   },
   "sidePortals": {
    "S": "side_exit_S",
    "N": "side_exit_N",
    "W": "side_exit_W"
   },
   "physics": {
    "profile": "dj",
    "constants": {
     "TICK_HZ": 20,
     "GRAVITY": 4,
     "MAX_FALL": 22,
     "BOUNCE_VY": -13,
     "SPRING_VY": -22,
     "JETPACK_VY": -36,
     "MOVE_ACCEL": 0.8,
     "AIR_DRAG": 0.92,
     "MAX_VX": 6,
     "PLATFORM_WIDTH": 60,
     "PLAYER_HALF_WIDTH": 23,
     "SPAWN_HEIGHT": 120,
     "FALL_MARGIN": 60,
     "AIR_CONTROL": "flat",
     "MOVE_FLAT": 10,
     "LANDING": "latched",
     "BOUNCE_IMPULSE": 32.29999959468838,
     "SPRING_IMPULSE": 68,
     "BROWN_IMPULSE": 32.29999959468838,
     "JETPACK_THRUST": 5,
     "JETPACK_TICKS": 100,
     "CATCH_BAND": 40.15,
     "WRAP": "edge",
     "PLATFORM_BEHAVIORS": {
      "blue": "moving",
      "brown": "breaking"
     },
     "BLUE_SPEED": 5,
     "POSITION_QUANTUM": 0.05
    }
   },
   "backExitSide": "W",
   "fallBehavior": "current"
  },
  "exits": [
   {
    "exit_id": "exit_S",
    "x": 4,
    "y": 5,
    "side": "S",
    "exitName": "exit_S",
    "targetRegion": "region_4_4",
    "isBackExit": false,
    "isTeleporter": false,
    "targetExitId": "region_4_3"
   },
   {
    "exit_id": "exit_N",
    "x": 4,
    "y": 0,
    "side": "N",
    "exitName": "exit_N",
    "targetRegion": "region_4_2",
    "isBackExit": false,
    "isTeleporter": false,
    "targetExitId": "region_4_3"
   },
   {
    "exit_id": "region_3_3",
    "x": 0,
    "y": 3,
    "side": "W",
    "exitName": "region_3_3",
    "targetRegion": "region_3_3",
    "targetExitId": "exit_E",
    "isBackExit": true,
    "isTeleporter": false
   }
  ]
 },
 "region_4_4": {
  "regionId": "region_4_4",
  "params": {
   "bounceLevel": {
    "id": "region_4_4",
    "size": {
     "width": 600,
     "height": 970
    },
    "platforms": [
     {
      "id": "p0",
      "x": 300,
      "y": 870,
      "type": "green"
     },
     {
      "id": "p1",
      "x": 300,
      "y": 780,
      "type": "green"
     },
     {
      "id": "p2",
      "x": 300,
      "y": 690,
      "type": "green"
     },
     {
      "id": "p3",
      "x": 300,
      "y": 600,
      "type": "green"
     },
     {
      "id": "p4",
      "x": 300,
      "y": 510,
      "type": "green"
     },
     {
      "id": "p5",
      "x": 300,
      "y": 420,
      "type": "green"
     },
     {
      "id": "p6",
      "x": 300,
      "y": 330,
      "type": "green"
     },
     {
      "id": "p7",
      "x": 300,
      "y": 240,
      "type": "green"
     },
     {
      "id": "p8",
      "x": 300,
      "y": 150,
      "type": "green"
     },
     {
      "id": "p9",
      "x": 300,
      "y": 60,
      "type": "brown"
     },
     {
      "id": "p10",
      "x": 185,
      "y": 690,
      "type": "green"
     }
    ],
    "springs": [],
    "jetpacks": [],
    "pickups": [
     {
      "id": "loc_0",
      "x": 300,
      "y": 490,
      "on": "p4"
     }
    ],
    "portals": [
     {
      "id": "side_exit_W",
      "x": 300,
      "y": 40,
      "on": "p9",
      "target_region": null,
      "direction": "left"
     },
     {
      "id": "side_exit_N",
      "x": 185,
      "y": 670,
      "on": "p10",
      "target_region": null,
      "direction": "up"
     }
    ]
   },
   "sidePortals": {
    "W": "side_exit_W",
    "N": "side_exit_N"
   },
   "physics": {
    "profile": "dj",
    "constants": {
     "TICK_HZ": 20,
     "GRAVITY": 4,
     "MAX_FALL": 22,
     "BOUNCE_VY": -13,
     "SPRING_VY": -22,
     "JETPACK_VY": -36,
     "MOVE_ACCEL": 0.8,
     "AIR_DRAG": 0.92,
     "MAX_VX": 6,
     "PLATFORM_WIDTH": 60,
     "PLAYER_HALF_WIDTH": 23,
     "SPAWN_HEIGHT": 120,
     "FALL_MARGIN": 60,
     "AIR_CONTROL": "flat",
     "MOVE_FLAT": 10,
     "LANDING": "latched",
     "BOUNCE_IMPULSE": 32.29999959468838,
     "SPRING_IMPULSE": 68,
     "BROWN_IMPULSE": 32.29999959468838,
     "JETPACK_THRUST": 5,
     "JETPACK_TICKS": 100,
     "CATCH_BAND": 40.15,
     "WRAP": "edge",
     "PLATFORM_BEHAVIORS": {
      "blue": "moving",
      "brown": "breaking"
     },
     "BLUE_SPEED": 5,
     "POSITION_QUANTUM": 0.05
    }
   },
   "backExitSide": "N",
   "fallBehavior": "current"
  },
  "exits": [
   {
    "exit_id": "exit_W",
    "x": 0,
    "y": 3,
    "side": "W",
    "exitName": "exit_W",
    "targetRegion": "region_3_4",
    "isBackExit": false,
    "isTeleporter": false,
    "targetExitId": "region_4_4"
   },
   {
    "exit_id": "region_4_3",
    "x": 4,
    "y": 0,
    "side": "N",
    "exitName": "region_4_3",
    "targetRegion": "region_4_3",
    "targetExitId": "exit_S",
    "isBackExit": true,
    "isTeleporter": false
   }
  ]
 },
 "region_4_2": {
  "regionId": "region_4_2",
  "params": {
   "bounceLevel": {
    "id": "region_4_2",
    "size": {
     "width": 600,
     "height": 1150
    },
    "platforms": [
     {
      "id": "p0",
      "x": 300,
      "y": 1050,
      "type": "green"
     },
     {
      "id": "p1",
      "x": 300,
      "y": 960,
      "type": "green"
     },
     {
      "id": "p2",
      "x": 300,
      "y": 870,
      "type": "green"
     },
     {
      "id": "p3",
      "x": 300,
      "y": 780,
      "type": "green"
     },
     {
      "id": "p4",
      "x": 300,
      "y": 690,
      "type": "green"
     },
     {
      "id": "p5",
      "x": 300,
      "y": 600,
      "type": "green"
     },
     {
      "id": "p6",
      "x": 300,
      "y": 510,
      "type": "blue",
      "sweep": {
       "min": 15,
       "max": 585
      }
     },
     {
      "id": "p7",
      "x": 300,
      "y": 420,
      "type": "green"
     },
     {
      "id": "p8",
      "x": 300,
      "y": 330,
      "type": "green"
     },
     {
      "id": "p9",
      "x": 300,
      "y": 240,
      "type": "green"
     },
     {
      "id": "p10",
      "x": 300,
      "y": 150,
      "type": "green"
     },
     {
      "id": "p11",
      "x": 300,
      "y": 60,
      "type": "green"
     }
    ],
    "springs": [],
    "jetpacks": [],
    "pickups": [
     {
      "id": "loc_0",
      "x": 300,
      "y": 760,
      "on": "p3"
     },
     {
      "id": "loc_1",
      "x": 300,
      "y": 670,
      "on": "p4"
     }
    ],
    "portals": [
     {
      "id": "side_exit_S",
      "x": 300,
      "y": 40,
      "on": "p11",
      "target_region": null,
      "direction": "down"
     }
    ]
   },
   "sidePortals": {
    "S": "side_exit_S"
   },
   "physics": {
    "profile": "dj",
    "constants": {
     "TICK_HZ": 20,
     "GRAVITY": 4,
     "MAX_FALL": 22,
     "BOUNCE_VY": -13,
     "SPRING_VY": -22,
     "JETPACK_VY": -36,
     "MOVE_ACCEL": 0.8,
     "AIR_DRAG": 0.92,
     "MAX_VX": 6,
     "PLATFORM_WIDTH": 60,
     "PLAYER_HALF_WIDTH": 23,
     "SPAWN_HEIGHT": 120,
     "FALL_MARGIN": 60,
     "AIR_CONTROL": "flat",
     "MOVE_FLAT": 10,
     "LANDING": "latched",
     "BOUNCE_IMPULSE": 32.29999959468838,
     "SPRING_IMPULSE": 68,
     "BROWN_IMPULSE": 32.29999959468838,
     "JETPACK_THRUST": 5,
     "JETPACK_TICKS": 100,
     "CATCH_BAND": 40.15,
     "WRAP": "edge",
     "PLATFORM_BEHAVIORS": {
      "blue": "moving",
      "brown": "breaking"
     },
     "BLUE_SPEED": 5,
     "POSITION_QUANTUM": 0.05
    }
   },
   "backExitSide": "S",
   "fallBehavior": "current"
  },
  "exits": [
   {
    "exit_id": "region_4_3",
    "x": 4,
    "y": 5,
    "side": "S",
    "exitName": "region_4_3",
    "targetRegion": "region_4_3",
    "targetExitId": "exit_N",
    "isBackExit": true,
    "isTeleporter": false
   }
  ]
 },
 "region_3_4": {
  "regionId": "region_3_4",
  "params": {
   "bounceLevel": {
    "id": "region_3_4",
    "size": {
     "width": 600,
     "height": 790
    },
    "platforms": [
     {
      "id": "p0",
      "x": 300,
      "y": 690,
      "type": "green"
     },
     {
      "id": "p1",
      "x": 300,
      "y": 600,
      "type": "green"
     },
     {
      "id": "p2",
      "x": 300,
      "y": 510,
      "type": "green"
     },
     {
      "id": "p3",
      "x": 300,
      "y": 420,
      "type": "green"
     },
     {
      "id": "p4",
      "x": 300,
      "y": 330,
      "type": "green"
     },
     {
      "id": "p5",
      "x": 300,
      "y": 240,
      "type": "green"
     },
     {
      "id": "p6",
      "x": 300,
      "y": 150,
      "type": "green"
     },
     {
      "id": "p7",
      "x": 300,
      "y": 60,
      "type": "brown"
     }
    ],
    "springs": [],
    "jetpacks": [],
    "pickups": [
     {
      "id": "loc_0",
      "x": 300,
      "y": 490,
      "on": "p2"
     }
    ],
    "portals": [
     {
      "id": "side_exit_E",
      "x": 300,
      "y": 40,
      "on": "p7",
      "target_region": null,
      "direction": "right"
     }
    ]
   },
   "sidePortals": {
    "E": "side_exit_E"
   },
   "physics": {
    "profile": "dj",
    "constants": {
     "TICK_HZ": 20,
     "GRAVITY": 4,
     "MAX_FALL": 22,
     "BOUNCE_VY": -13,
     "SPRING_VY": -22,
     "JETPACK_VY": -36,
     "MOVE_ACCEL": 0.8,
     "AIR_DRAG": 0.92,
     "MAX_VX": 6,
     "PLATFORM_WIDTH": 60,
     "PLAYER_HALF_WIDTH": 23,
     "SPAWN_HEIGHT": 120,
     "FALL_MARGIN": 60,
     "AIR_CONTROL": "flat",
     "MOVE_FLAT": 10,
     "LANDING": "latched",
     "BOUNCE_IMPULSE": 32.29999959468838,
     "SPRING_IMPULSE": 68,
     "BROWN_IMPULSE": 32.29999959468838,
     "JETPACK_THRUST": 5,
     "JETPACK_TICKS": 100,
     "CATCH_BAND": 40.15,
     "WRAP": "edge",
     "PLATFORM_BEHAVIORS": {
      "blue": "moving",
      "brown": "breaking"
     },
     "BLUE_SPEED": 5,
     "POSITION_QUANTUM": 0.05
    }
   },
   "backExitSide": "E",
   "fallBehavior": "current"
  },
  "exits": [
   {
    "exit_id": "region_4_4",
    "x": 7,
    "y": 3,
    "side": "E",
    "exitName": "region_4_4",
    "targetRegion": "region_4_4",
    "targetExitId": "exit_W",
    "isBackExit": true,
    "isTeleporter": false
   }
  ]
 }
};
window.__DJ_START_REGION = window.__DJ_START_REGION || "region_4_4";
