// shape_hit_test.c — shape-accurate point-in-shape testing.
//
// Moved here from tag_stubs.c so the same hit-test code is available in
// graphics builds (used by ng_update_button_states_in_dl in tag.c for
// AVM1 button hover/click dispatch). All deps are graphics-friendly:
// dictionary, transform_data, text_data, glyph_data, shape_data live in
// every build mode (renderer-generated for graphics, NO_GRAPHICS-side
// generated for trace).
//
// Compiled in NO_GRAPHICS, HEADLESS_GRAPHICS, and pure graphics builds.

#include <tag.h>
#include <swf.h>
#include <common.h>
#include <math.h>
#include <stdlib.h>
#include <stdint.h>

// Globals defined elsewhere depending on build mode (swf.c, swf_core.c, swf_headless.c, tag_stubs.c)
extern Character* dictionary;
extern DisplayObject* display_list;
extern size_t max_depth;

// Per-test arrays generated by the recompiler (draws.c / tagMain.c)
extern float transform_data[][16];
extern u32 shape_data[][4];
extern u32 glyph_data[][1];
extern u32 text_data[];

// From ng_shared.c (compiled in all modes)
extern int ng_find_textfield(size_t char_id);
extern int ng_find_char_path(size_t char_id, size_t* out_offset, size_t* out_size);
extern int ng_find_morph_path(size_t char_id, size_t* out_offset, size_t* out_size);
extern int ng_uses_nonzero_winding(size_t char_id);
extern void ng_getTextFieldBounds(int tf_idx, s32* xmin, s32* xmax, s32* ymin, s32* ymax);
extern int ng_getCharBoundsForRatio(size_t char_id, u16 ratio, s32* out_xmin, s32* out_xmax, s32* out_ymin, s32* out_ymax);

// ---------------------------------------------------------------------------
// Display-list entry to DisplayObject* (encoded entry index = parent<<20 | child)
// ---------------------------------------------------------------------------
static DisplayObject* ng_entry_to_obj(size_t entry_idx)
{
	if (entry_idx == (size_t)-1) return NULL;
	size_t parent_depth = entry_idx >> 20;
	size_t child_depth  = entry_idx & 0xFFFFF;
	if (parent_depth == 0) {
		// Root level. Depth 0 is a valid root-level placement (Ming
		// SWFDisplayItem_setDepth(it, 0)); the char_id check below guards
		// against unused slots.
		if (child_depth > max_depth) return NULL;
		if (display_list[child_depth].char_id == 0) return NULL;
		return &display_list[child_depth];
	} else {
		// Level-1 nested: parent is at display_list[parent_depth]
		if (parent_depth > max_depth) return NULL;
		DisplayObject* parent = &display_list[parent_depth];
		if (parent->sprite_display_list == NULL) return NULL;
		if (child_depth < 1 || child_depth > parent->sprite_max_depth) return NULL;
		if (parent->sprite_display_list[child_depth].char_id == 0) return NULL;
		return &parent->sprite_display_list[child_depth];
	}
}

// ---------------------------------------------------------------------------
// Render-format matrix accessor (f32 a/b/c/d, i32 twips tx/ty)
// ---------------------------------------------------------------------------
// Variant: f32 a/b/c/d, i32 twips tx/ty (matches Ruffle render Matrix)
int ng_getMatrixFromEntry_render(size_t entry_idx,
    float* out_a, float* out_b, float* out_c, float* out_d,
    int32_t* out_tx_twips, int32_t* out_ty_twips)
{
	DisplayObject* obj = ng_entry_to_obj(entry_idx);
	if (!obj) return 0;
	u32 tid = obj->transform_id;
	if (out_a)  *out_a  = transform_data[tid][0];
	if (out_b)  *out_b  = transform_data[tid][1];
	if (out_c)  *out_c  = transform_data[tid][4];
	if (out_d)  *out_d  = transform_data[tid][5];
	if (out_tx_twips) *out_tx_twips = (int32_t)rintf(transform_data[tid][12]);
	if (out_ty_twips) *out_ty_twips = (int32_t)rintf(transform_data[tid][13]);
	return 1;
}

extern u32 shape_data[][4];
extern u32 glyph_data[][1];
extern u32 text_data[];

// Test if a point is inside a single triangle (barycentric coordinates)
// ---------------------------------------------------------------------------
// Vector-path hit testing: winding number algorithm
// ---------------------------------------------------------------------------

// Weak default: overridden by draws.c when shapes are present.
// Older generated code may lack path_data; this prevents linker errors.
__attribute__((weak)) float path_data[1][3] = {{0}};


// Winding number contribution from a line segment (ray-cast along +x axis).
// Returns +1 (downward crossing), -1 (upward crossing), or 0 (no crossing).
static int winding_number_line(double px, double py,
    double ax, double ay, double bx, double by)
{
	// Check if horizontal ray from (px, py) to +inf crosses segment (a → b)
	if (ay == by) return 0;  // horizontal segment — no crossing
	int downward = (by > ay) ? 1 : 0;
	double y_min = downward ? ay : by;
	double y_max = downward ? by : ay;
	// Point must be in [y_min, y_max) range (half-open for consistent endpoints)
	if (py < y_min || py >= y_max) return 0;
	// Check if point is to the left of the segment (ray crosses it)
	double t = (py - ay) / (by - ay);
	double x_at_t = ax + t * (bx - ax);
	if (px < x_at_t) return downward ? 1 : -1;
	return 0;
}

// Winding number contribution from a quadratic bezier curve.
// P0=(ax,ay), P1=(cx,cy) control, P2=(bx,by) anchor.
// Uses y-monotonic curve splitting for numerical stability at extrema.
// Port of Ruffle's shape_utils.rs winding_number_curve + solve_quadratic.
static int winding_number_curve(double px, double py,
    double ax, double ay, double cx, double cy, double bx, double by)
{
	// Translate so test point is at origin; ray goes along +x at y=0
	double x0 = ax - px, y0 = ay - py;
	double x1 = cx - px, y1 = cy - py;
	double x2 = bx - px, y2 = by - py;

	// Quick reject: all control points on same side of ray, or all to the left
	if ((y0 < 0.0 && y1 < 0.0 && y2 < 0.0) ||
	    (y0 > 0.0 && y1 > 0.0 && y2 > 0.0) ||
	    (x0 <= 0.0 && x1 <= 0.0 && x2 <= 0.0))
		return 0;

	// Quadratic y(t) = a*t² + b*t + c, solve y(t) = 0
	double a = y0 - 2.0*y1 + y2;
	double b = 2.0*(y1 - y0);
	double c_v = y0;

	// Solve with Citardauq root ordering: t0=ascending, t1=descending
	double t0 = 0.0/0.0, t1 = 0.0/0.0;  // NaN = invalid
	if (fabs(a) <= 1e-7) {
		// Near-linear
		if (fabs(b) < 1e-10) return 0;
		double r = -c_v / b;
		if (b >= 0.0) t1 = r; else t0 = r;
	} else {
		double disc = b*b - 4.0*a*c_v;
		if (disc < 0.0) return 0;
		disc = sqrt(disc);
		if (b >= 0.0) {
			t0 = (-b - disc) / (2.0*a);
			t1 = (-b + disc) / (2.0*a);
		} else {
			t0 = (-b - disc) / (2.0*a);
			t1 = (-b + disc) / (2.0*a);
		}
	}

	int t0_ok = isfinite(t0);
	int t1_ok = isfinite(t1);
	if (!t0_ok && !t1_ok) return 0;

	// Y-monotonic splitting: split at y-extremum t_ext = -b/(2a)
	int winding = 0;
	double qax = x0 - 2.0*x1 + x2;
	double qbx = 2.0*(x1 - x0);
	double t_ext = (fabs(a) > 1e-10) ? (-0.5 * b / a) : -1.0;
	int is_mono = (t_ext <= 0.0 || t_ext >= 1.0);

	if (a >= 0.0) {
		// Downward-opening parabola: y has a MINIMUM at t_ext
		double y_min = is_mono ? fmin(y0, y2) : (a*t_ext*t_ext + b*t_ext + c_v);

		// First subcurve: upward (ascending root t0). Ray must be in [y_min, y0)
		if (t0_ok && 0.0 >= y_min && 0.0 < y0) {
			double x = x0 + qbx*t0 + qax*t0*t0;
			if (x > 0.0) winding += 1;
		}
		// Second subcurve: downward (descending root t1). Ray must be in [y_min, y2)
		if (t1_ok && 0.0 >= y_min && 0.0 < y2) {
			double x = x0 + qbx*t1 + qax*t1*t1;
			if (x > 0.0) winding -= 1;
		}
	} else {
		// Upward-opening parabola: y has a MAXIMUM at t_ext
		double y_max = is_mono ? fmax(y0, y2) : (a*t_ext*t_ext + b*t_ext + c_v);

		// First subcurve: downward (descending root t1). Ray must be in [y0, y_max)
		if (t1_ok && 0.0 >= y0 && 0.0 < y_max) {
			double x = x0 + qbx*t1 + qax*t1*t1;
			if (x > 0.0) winding -= 1;
		}
		// Second subcurve: upward (ascending root t0). Ray must be in [y2, y_max)
		if (t0_ok && 0.0 >= y2 && 0.0 < y_max) {
			double x = x0 + qbx*t0 + qax*t0*t0;
			if (x > 0.0) winding += 1;
		}
	}

	return winding;
}

// Path-based fill hit test: test if point is inside the shape's fill paths.
// Uses winding number accumulation from path_data edges.
// Returns 1 if hit, 0 if miss.
// ---------------------------------------------------------------------------
// Stroke distance testing: closest-point-to-path for stroke hit detection
// ---------------------------------------------------------------------------

// Squared distance from point P to line segment A→B.
static double dist_sq_point_to_segment(double px, double py,
    double ax, double ay, double bx, double by)
{
	double dx = bx - ax, dy = by - ay;
	double len_sq = dx*dx + dy*dy;
	if (len_sq < 1e-10) {
		// Degenerate segment (zero length)
		double ex = px - ax, ey = py - ay;
		return ex*ex + ey*ey;
	}
	// Project P onto line AB, clamped to [0,1]
	double t = ((px - ax)*dx + (py - ay)*dy) / len_sq;
	if (t < 0.0) t = 0.0;
	if (t > 1.0) t = 1.0;
	double cx = ax + t*dx - px;
	double cy = ay + t*dy - py;
	return cx*cx + cy*cy;
}

// Squared distance from point P to quadratic bezier curve P0→P1(ctrl)→P2(anchor).
// Finds t where (P - C(t)) · C'(t) = 0 by solving a cubic, then tests endpoints.
static double dist_sq_point_to_curve(double px, double py,
    double x0, double y0, double x1, double y1, double x2, double y2)
{
	// Coefficients for C(t) = (1-t)²P0 + 2t(1-t)P1 + t²P2
	// C(t) = P0 + 2t(P1-P0) + t²(P0-2P1+P2) = P0 + t*B + t²*A
	double ax = x0 - 2.0*x1 + x2, ay_c = y0 - 2.0*y1 + y2;
	double bxc = 2.0*(x1 - x0), byc = 2.0*(y1 - y0);
	double mx = x0 - px, my = y0 - py;

	// (P - C(t)) · C'(t) = 0, where C'(t) = B + 2tA
	// Expanding: cubic in t: a3*t³ + a2*t² + a1*t + a0 = 0
	double a3 = 2.0*(ax*ax + ay_c*ay_c);
	double a2 = 3.0*(ax*bxc + ay_c*byc);
	double a1 = bxc*bxc + byc*byc + 2.0*(ax*mx + ay_c*my);
	double a0 = bxc*mx + byc*my;

	// Find minimum distance: check endpoints and all cubic roots in [0,1]
	double min_d = mx*mx + my*my;  // dist at t=0
	double e2x = x2 - px, e2y = y2 - py;
	double d_end = e2x*e2x + e2y*e2y;
	if (d_end < min_d) min_d = d_end;

	// Solve cubic a3*t³ + a2*t² + a1*t + a0 = 0
	if (fabs(a3) > 1e-10) {
		// Reduce to depressed cubic: t³ + pt + q = 0
		double inv_a3 = 1.0 / a3;
		double p = (3.0*a3*a1 - a2*a2) / (3.0*a3*a3);
		double q = (2.0*a2*a2*a2 - 9.0*a3*a2*a1 + 27.0*a3*a3*a0) / (27.0*a3*a3*a3);
		double disc = q*q/4.0 + p*p*p/27.0;
		double shift = -a2 / (3.0*a3);

		double roots[3];
		int n_roots = 0;

		if (disc > 1e-10) {
			// One real root
			double sq = sqrt(disc);
			double u = cbrt(-q/2.0 + sq);
			double v = cbrt(-q/2.0 - sq);
			roots[n_roots++] = u + v + shift;
		} else if (disc < -1e-10) {
			// Three real roots (trigonometric solution)
			double r = sqrt(-p*p*p / 27.0);
			double theta = acos(-q / (2.0*r));
			double cr = cbrt(r);
			roots[n_roots++] = 2.0*cr*cos(theta/3.0) + shift;
			roots[n_roots++] = 2.0*cr*cos((theta + 2.0*3.14159265358979323846)/3.0) + shift;
			roots[n_roots++] = 2.0*cr*cos((theta + 4.0*3.14159265358979323846)/3.0) + shift;
		} else {
			// Double or triple root
			if (fabs(q) > 1e-10) {
				double u = cbrt(-q/2.0);
				roots[n_roots++] = 2.0*u + shift;
				roots[n_roots++] = -u + shift;
			} else {
				roots[n_roots++] = shift;
			}
		}

		for (int i = 0; i < n_roots; i++) {
			double t = roots[i];
			if (t > 0.0 && t < 1.0) {
				double it = 1.0 - t;
				double cx = it*it*x0 + 2.0*it*t*x1 + t*t*x2 - px;
				double cy = it*it*y0 + 2.0*it*t*y1 + t*t*y2 - py;
				double d = cx*cx + cy*cy;
				if (d < min_d) min_d = d;
			}
		}
	} else if (fabs(a2) > 1e-10) {
		// Quadratic: a2*t² + a1*t + a0 = 0
		double disc = a1*a1 - 4.0*a2*a0;
		if (disc >= 0.0) {
			double sq = sqrt(disc);
			double r1 = (-a1 - sq) / (2.0*a2);
			double r2 = (-a1 + sq) / (2.0*a2);
			for (int i = 0; i < 2; i++) {
				double t = (i == 0) ? r1 : r2;
				if (t > 0.0 && t < 1.0) {
					double it = 1.0 - t;
					double cx = it*it*x0 + 2.0*it*t*x1 + t*t*x2 - px;
					double cy = it*it*y0 + 2.0*it*t*y1 + t*t*y2 - py;
					double d = cx*cx + cy*cy;
					if (d < min_d) min_d = d;
				}
			}
		}
	} else if (fabs(a1) > 1e-10) {
		// Linear: a1*t + a0 = 0
		double t = -a0 / a1;
		if (t > 0.0 && t < 1.0) {
			double it = 1.0 - t;
			double cx = it*it*x0 + 2.0*it*t*x1 + t*t*x2 - px;
			double cy = it*it*y0 + 2.0*it*t*y1 + t*t*y2 - py;
			double d = cx*cx + cy*cy;
			if (d < min_d) min_d = d;
		}
	}

	return min_d;
}

// Path-based stroke hit test: test if point is within stroke width of any edge.
// Returns 1 if hit, 0 if miss.
static int ng_hitTestPathStroke(size_t path_offset, size_t path_size,
    double local_x, double local_y)
{
	double cursor_x = 0.0, cursor_y = 0.0;
	double line_width = 0.0;  // full width in local coords
	int has_line = 0;

	size_t end = path_offset + path_size;
	for (size_t i = path_offset; i < end; i++) {
		float cmd = path_data[i][0];
		if (cmd == 1.0f) {
			// StyleChange fills — skip
			if (i + 1 < end && path_data[i+1][0] == 1.5f) {
				i++;
				int line_style = (int)path_data[i][1];
				line_width = (double)path_data[i][2];
				has_line = (line_style > 0 && line_width > 0.0);
				// Minimum stroke width: 1 pixel = 20 twips
				if (has_line && line_width < 20.0) line_width = 20.0;
			}
		}
		else if (cmd == 5.0f) {
			cursor_x = (double)path_data[i][1];
			cursor_y = (double)path_data[i][2];
		}
		else if (cmd == 2.0f && has_line) {
			double nx = (double)path_data[i][1], ny = (double)path_data[i][2];
			double half_w = line_width * 0.5;
			if (dist_sq_point_to_segment(local_x, local_y, cursor_x, cursor_y, nx, ny) <= half_w * half_w)
				return 1;
			cursor_x = nx; cursor_y = ny;
		}
		else if (cmd == 2.0f) {
			cursor_x = (double)path_data[i][1]; cursor_y = (double)path_data[i][2];
		}
		else if (cmd == 3.0f && i + 1 < end) {
			double cx = (double)path_data[i][1], cy = (double)path_data[i][2];
			i++;
			double nx = (double)path_data[i][1], ny = (double)path_data[i][2];
			if (has_line) {
				double half_w = line_width * 0.5;
				if (dist_sq_point_to_curve(local_x, local_y, cursor_x, cursor_y, cx, cy, nx, ny) <= half_w * half_w)
					return 1;
			}
			cursor_x = nx; cursor_y = ny;
		}
		else if (cmd == 0.0f) break;
	}
	return 0;
}

static int ng_hitTestPathFill(size_t char_id, size_t path_offset, size_t path_size,
    double local_x, double local_y)
{
	// Accumulate winding numbers per fill style
	// (SWF shapes have few fill styles, typically < 10)
	int fill_winding[64] = {0};
	int max_fill = 0;

	int cur_fill0 = 0, cur_fill1 = 0;
	double cursor_x = 0.0, cursor_y = 0.0;

	size_t end = path_offset + path_size;
	for (size_t i = path_offset; i < end; i++) {
		float cmd = path_data[i][0];

		if (cmd == 1.0f) {
			// StyleChange: {1, fill0, fill1}
			cur_fill0 = (int)path_data[i][1];
			cur_fill1 = (int)path_data[i][2];
			if (cur_fill0 > max_fill) max_fill = cur_fill0;
			if (cur_fill1 > max_fill) max_fill = cur_fill1;
			// Skip line style entry (1.5)
			if (i + 1 < end && path_data[i+1][0] == 1.5f) i++;
		}
		else if (cmd == 5.0f) {
			// MoveTo: {5, x, y}
			cursor_x = (double)path_data[i][1];
			cursor_y = (double)path_data[i][2];
		}
		else if (cmd == 2.0f) {
			// LineTo: {2, x, y}
			double nx = (double)path_data[i][1];
			double ny = (double)path_data[i][2];

			// fill1 (left fill): forward direction
			if (cur_fill1 > 0 && cur_fill1 < 64) {
				fill_winding[cur_fill1] += winding_number_line(local_x, local_y,
					cursor_x, cursor_y, nx, ny);
			}
			// fill0 (right fill): negate forward winding (NOT reverse arguments,
			// because reversing shifts endpoints between t=0/t=1, breaking half-open interval)
			if (cur_fill0 > 0 && cur_fill0 < 64) {
				fill_winding[cur_fill0] -= winding_number_line(local_x, local_y,
					cursor_x, cursor_y, nx, ny);
			}
			cursor_x = nx;
			cursor_y = ny;
		}
		else if (cmd == 3.0f && i + 1 < end) {
			// CurveTo: {3, ctrl_x, ctrl_y} + {4, anchor_x, anchor_y}
			double cx = (double)path_data[i][1];
			double cy = (double)path_data[i][2];
			i++;
			double nx = (double)path_data[i][1];
			double ny = (double)path_data[i][2];

			if (cur_fill1 > 0 && cur_fill1 < 64) {
				fill_winding[cur_fill1] += winding_number_curve(local_x, local_y,
					cursor_x, cursor_y, cx, cy, nx, ny);
			}
			if (cur_fill0 > 0 && cur_fill0 < 64) {
				fill_winding[cur_fill0] -= winding_number_curve(local_x, local_y,
					cursor_x, cursor_y, cx, cy, nx, ny);
			}
			cursor_x = nx;
			cursor_y = ny;
		}
		else if (cmd == 0.0f) {
			break;  // End
		}
	}

	// Check if point is inside any fill
	int nonzero = ng_uses_nonzero_winding(char_id);
	for (int f = 1; f <= max_fill && f < 64; f++) {
		if (nonzero) {
			if (fill_winding[f] != 0) return 1;
		} else {
			if ((fill_winding[f] & 1) != 0) return 1;
		}
	}
	return 0;
}

// Morph path hit test: walks interleaved path data, interpolates by ratio, tests fills + strokes.
// Interleaved format: geometric/line-width entries are followed by {9.0, end_a, end_b}.
static int ng_hitTestMorphPath(size_t char_id, size_t path_offset, size_t path_size,
    double local_x, double local_y, u16 ratio)
{
	double t = (double)ratio / 65535.0;
	double ot = 1.0 - t;

	int fill_winding[64] = {0};
	int max_fill = 0;
	int cur_fill0 = 0, cur_fill1 = 0;
	double line_width = 0.0;
	int has_line = 0;
	double cursor_x = 0.0, cursor_y = 0.0;
	int stroke_hit = 0;

	size_t i = path_offset;
	size_t end = path_offset + path_size;

	while (i < end) {
		float cmd = path_data[i][0];

		if (cmd == 0.0f) break;

		if (cmd == 1.0f) {
			// StyleChange fills (no interpolation)
			cur_fill0 = (int)path_data[i][1];
			cur_fill1 = (int)path_data[i][2];
			if (cur_fill0 > max_fill) max_fill = cur_fill0;
			if (cur_fill1 > max_fill) max_fill = cur_fill1;
			i++;
			continue;
		}

		if (cmd == 1.5f) {
			// StyleChange line (start width)
			int line_style = (int)path_data[i][1];
			double start_w = (double)path_data[i][2];
			i++;
			// Read morph end width (cmd == 9.0)
			double end_w = start_w;
			if (i < end && path_data[i][0] == 9.0f) {
				end_w = (double)path_data[i][2];
				i++;
			}
			line_width = ot * start_w + t * end_w;
			has_line = (line_style > 0);
			if (has_line && line_width < 20.0) line_width = 20.0;
			continue;
		}

		if (cmd == 5.0f) {
			// MoveTo (start)
			double sx = (double)path_data[i][1], sy = (double)path_data[i][2];
			i++;
			double ex = sx, ey = sy;
			if (i < end && path_data[i][0] == 9.0f) {
				ex = (double)path_data[i][1]; ey = (double)path_data[i][2];
				i++;
			}
			cursor_x = ot * sx + t * ex;
			cursor_y = ot * sy + t * ey;
			continue;
		}

		if (cmd == 2.0f) {
			// LineTo (start)
			double sx = (double)path_data[i][1], sy = (double)path_data[i][2];
			i++;
			double ex = sx, ey = sy;
			if (i < end && path_data[i][0] == 9.0f) {
				ex = (double)path_data[i][1]; ey = (double)path_data[i][2];
				i++;
			}
			double nx = ot * sx + t * ex;
			double ny = ot * sy + t * ey;

			// Fill winding
			int w = winding_number_line(local_x, local_y, cursor_x, cursor_y, nx, ny);
			if (cur_fill1 > 0 && cur_fill1 < 64) fill_winding[cur_fill1] += w;
			if (cur_fill0 > 0 && cur_fill0 < 64) fill_winding[cur_fill0] -= w;

			// Stroke
			if (has_line && !stroke_hit) {
				double half_w = line_width * 0.5;
				if (dist_sq_point_to_segment(local_x, local_y, cursor_x, cursor_y, nx, ny) <= half_w * half_w)
					stroke_hit = 1;
			}

			cursor_x = nx;
			cursor_y = ny;
			continue;
		}

		if (cmd == 3.0f) {
			// CurveTo control (start)
			double scx = (double)path_data[i][1], scy = (double)path_data[i][2];
			i++;
			double ecx = scx, ecy = scy;
			if (i < end && path_data[i][0] == 9.0f) {
				ecx = (double)path_data[i][1]; ecy = (double)path_data[i][2];
				i++;
			}
			double ctrl_x = ot * scx + t * ecx;
			double ctrl_y = ot * scy + t * ecy;

			// Expect anchor (cmd == 4.0)
			if (i >= end || path_data[i][0] != 4.0f) { continue; }
			double sax = (double)path_data[i][1], say = (double)path_data[i][2];
			i++;
			double eax = sax, eay = say;
			if (i < end && path_data[i][0] == 9.0f) {
				eax = (double)path_data[i][1]; eay = (double)path_data[i][2];
				i++;
			}
			double anchor_x = ot * sax + t * eax;
			double anchor_y = ot * say + t * eay;

			// Fill winding
			int w = winding_number_curve(local_x, local_y, cursor_x, cursor_y, ctrl_x, ctrl_y, anchor_x, anchor_y);
			if (cur_fill1 > 0 && cur_fill1 < 64) fill_winding[cur_fill1] += w;
			if (cur_fill0 > 0 && cur_fill0 < 64) fill_winding[cur_fill0] -= w;

			// Stroke
			if (has_line && !stroke_hit) {
				double half_w = line_width * 0.5;
				if (dist_sq_point_to_curve(local_x, local_y, cursor_x, cursor_y, ctrl_x, ctrl_y, anchor_x, anchor_y) <= half_w * half_w)
					stroke_hit = 1;
			}

			cursor_x = anchor_x;
			cursor_y = anchor_y;
			continue;
		}

		i++;  // skip unknown
	}

	// Check fills
	int nonzero = ng_uses_nonzero_winding(char_id);
	for (int f = 1; f <= max_fill && f < 64; f++) {
		if (nonzero) {
			if (fill_winding[f] != 0) return 1;
		} else {
			if ((fill_winding[f] & 1) != 0) return 1;
		}
	}

	return stroke_hit;
}

static int pit(double px, double py,
               double ax, double ay, double bx, double by, double cx, double cy)
{
	double d1 = (px - bx) * (ay - by) - (ax - bx) * (py - by);
	double d2 = (px - cx) * (by - cy) - (bx - cx) * (py - cy);
	double d3 = (px - ax) * (cy - ay) - (cx - ax) * (py - ay);
	int has_neg = (d1 < 0) || (d2 < 0) || (d3 < 0);
	int has_pos = (d1 > 0) || (d2 > 0) || (d3 > 0);
	if (has_neg && has_pos) return 0;

	// Check for shared-edge case: if exactly one d is zero, the point is
	// on a triangle edge. Use a fill rule to assign it to exactly one of
	// the two triangles sharing that edge, preventing double-counting that
	// breaks even-odd winding on earcut bridge edges.
	int zeros = (d1 == 0.0) + (d2 == 0.0) + (d3 == 0.0);
	if (zeros == 1) {
		// Identify the edge: d1=0 → edge AB, d2=0 → edge BC, d3=0 → edge CA
		double ex, ey;
		if (d1 == 0.0) { ex = bx - ax; ey = by - ay; }
		else if (d2 == 0.0) { ex = cx - bx; ey = cy - by; }
		else { ex = ax - cx; ey = ay - cy; }
		// Include if edge goes upward (ey > 0) or rightward when horizontal
		if (ey > 0.0) return 1;
		if (ey < 0.0) return 0;
		return (ex > 0.0) ? 1 : 0;
	}

	return 1;  // Strictly inside or on a vertex
}

// Morph end vertex data (for interpolated shape hit testing)
extern float morph_end_shape_data[][2];

// Test a point (in twips, parent-accumulated matrix space) against a char's shape triangles.
// ma..mty is the child's accumulated world matrix (mapping local twips → test space).
// ratio: morph ratio (0=start, 65535=end). Ignored for non-morph shapes.
// Returns 1 if hit, 0 if miss.
int ng_hitTestShapeChar(size_t char_id, u16 ratio,
    double ma, double mb, double mc_m, double md, double mtx, double mty,
    double test_x, double test_y)
{
	// EditText (text field): hit test against bounds rectangle
	int tf_idx = ng_find_textfield(char_id);
	if (tf_idx >= 0) {
		double det = ma * md - mb * mc_m;
		if (det == 0.0) return 0;
		double inv_det = 1.0 / det;
		double sx = test_x - mtx;
		double sy = test_y - mty;
		double local_x = ( md * sx - mc_m * sy) * inv_det;
		double local_y = (-mb * sx + ma  * sy) * inv_det;
		s32 _htfxmin, _htfxmax, _htfymin, _htfymax;
		ng_getTextFieldBounds(tf_idx, &_htfxmin, &_htfxmax, &_htfymin, &_htfymax);
		double xmin = (double)_htfxmin;
		double xmax = (double)_htfxmax;
		double ymin = (double)_htfymin;
		double ymax = (double)_htfymax;
		return (local_x >= xmin && local_x <= xmax && local_y >= ymin && local_y <= ymax);
	}

	Character* ch = &dictionary[char_id];

	// Static text (DefineText/DefineText2): per-glyph hit testing
	if (ch->type == CHAR_TYPE_TEXT) {
		size_t ts = ch->text_start;
		size_t tc = ch->text_size;
		u32 tf_base = ch->transform_start;
		for (size_t j = 0; j < tc; j++) {
			// glyph_data: 4 values per glyph (tri_offset, tri_size, path_offset, path_size)
			size_t gi = 4 * (size_t)text_data[ts + j];
			size_t glyph_offset = (size_t)glyph_data[gi][0];
			size_t glyph_size = (size_t)glyph_data[gi + 1][0];
			size_t glyph_path_offset = (size_t)glyph_data[gi + 2][0];
			size_t glyph_path_size = (size_t)glyph_data[gi + 3][0];
			if (glyph_size < 3 && glyph_path_size < 3) continue;  // no data
			// Compose parent matrix with glyph positioning transform
			u32 gtid = tf_base + (u32)j;
			double ga = (double)transform_data[gtid][0];
			double gb = (double)transform_data[gtid][1];
			double gc = (double)transform_data[gtid][4];
			double gd = (double)transform_data[gtid][5];
			double gtx_v = (double)transform_data[gtid][12];
			double gty_v = (double)transform_data[gtid][13];
			double na = ma*ga + mc_m*gb, nb = mb*ga + md*gb;
			double nc = ma*gc + mc_m*gd, nd = mb*gc + md*gd;
			double ntx = ma*gtx_v + mc_m*gty_v + mtx;
			double nty = mb*gtx_v + md*gty_v + mty;
			// Inverse transform test point to glyph-local space
			double det = na * nd - nb * nc;
			if (det == 0.0) continue;
			double inv_det = 1.0 / det;
			double sx = test_x - ntx;
			double sy = test_y - nty;
			double local_x = ( nd * sx - nc * sy) * inv_det;
			double local_y = (-nb * sx + na * sy) * inv_det;
			// Try path-based glyph hit test first (exact curves)
			if (glyph_path_size >= 3) {
				// Font glyphs use non-zero winding (TTF convention)
				int glyph_winding = 0;
				double g_cursor_x = 0, g_cursor_y = 0;
				int g_fill1 = 0;
				for (size_t pi = glyph_path_offset; pi < glyph_path_offset + glyph_path_size; pi++) {
					float pcmd = path_data[pi][0];
					if (pcmd == 1.0f) { g_fill1 = (int)path_data[pi][2]; if (pi+1 < glyph_path_offset+glyph_path_size && path_data[pi+1][0]==1.5f) pi++; }
					else if (pcmd == 5.0f) { g_cursor_x = (double)path_data[pi][1]; g_cursor_y = (double)path_data[pi][2]; }
					else if (pcmd == 2.0f && g_fill1) {
						double gnx = (double)path_data[pi][1], gny = (double)path_data[pi][2];
						glyph_winding += winding_number_line(local_x, local_y, g_cursor_x, g_cursor_y, gnx, gny);
						g_cursor_x = gnx; g_cursor_y = gny;
					}
					else if (pcmd == 3.0f && pi+1 < glyph_path_offset+glyph_path_size && g_fill1) {
						double gcx = (double)path_data[pi][1], gcy = (double)path_data[pi][2];
						pi++;
						double gnx = (double)path_data[pi][1], gny = (double)path_data[pi][2];
						glyph_winding += winding_number_curve(local_x, local_y, g_cursor_x, g_cursor_y, gcx, gcy, gnx, gny);
						g_cursor_x = gnx; g_cursor_y = gny;
					}
					else if (pcmd == 0.0f) break;
				}
				if (glyph_winding != 0) return 1;  // non-zero winding = inside glyph
				continue;  // path test is authoritative, skip triangle fallback
			}
			// Fallback: test against glyph triangles
			size_t num_tris = glyph_size / 3;
			for (size_t t = 0; t < num_tris; t++) {
				const u32* v0 = shape_data[glyph_offset + t*3 + 0];
				const u32* v1 = shape_data[glyph_offset + t*3 + 1];
				const u32* v2 = shape_data[glyph_offset + t*3 + 2];
				double ax = (double)*(const float*)&v0[0];
				double ay = (double)*(const float*)&v0[1];
				double bx = (double)*(const float*)&v1[0];
				double by = (double)*(const float*)&v1[1];
				double cx = (double)*(const float*)&v2[0];
				double cy = (double)*(const float*)&v2[1];
				if (pit(local_x, local_y, ax, ay, bx, by, cx, cy))
					return 1;
			}
		}
		return 0;
	}

	int is_morph = (ch->type == CHAR_TYPE_MORPH_SHAPE);
	if (ch->type != CHAR_TYPE_SHAPE && !is_morph) return 0;

	// Morph shapes: try path-based hit testing first, fall back to bounds
	if (is_morph) {
		size_t mp_offset, mp_size;
		if (ng_find_morph_path(char_id, &mp_offset, &mp_size)) {
			double det = ma * md - mb * mc_m;
			if (det == 0.0) return 0;
			double inv_det = 1.0 / det;
			double bsx = test_x - mtx;
			double bsy = test_y - mty;
			double local_x = ( md * bsx - mc_m * bsy) * inv_det;
			double local_y = (-mb * bsx + ma  * bsy) * inv_det;
			return ng_hitTestMorphPath(char_id, mp_offset, mp_size, local_x, local_y, ratio);
		}
		// Fallback: interpolated bounds-based hit testing
		s32 bxmin, bxmax, bymin, bymax;
		if (ng_getCharBoundsForRatio(char_id, ratio, &bxmin, &bxmax, &bymin, &bymax)) {
			double det = ma * md - mb * mc_m;
			if (det == 0.0) return 0;
			double inv_det = 1.0 / det;
			double bsx = test_x - mtx;
			double bsy = test_y - mty;
			double local_x = ( md * bsx - mc_m * bsy) * inv_det;
			double local_y = (-mb * bsx + ma  * bsy) * inv_det;
			return (local_x >= (double)bxmin && local_x <= (double)bxmax &&
			        local_y >= (double)bymin && local_y <= (double)bymax);
		}
		return 0;
	}

	// Vector-path hit testing for fills and strokes
	{
		size_t p_offset, p_size;
		if (ng_find_char_path(char_id, &p_offset, &p_size)) {
			double det = ma * md - mb * mc_m;
			if (det == 0.0) return 0;
			double inv_det = 1.0 / det;
			double sx = test_x - mtx;
			double sy = test_y - mty;
			double local_x = ( md * sx - mc_m * sy) * inv_det;
			double local_y = (-mb * sx + ma  * sy) * inv_det;
			if (ng_hitTestPathFill(char_id, p_offset, p_size, local_x, local_y))
				return 1;
			if (ng_hitTestPathStroke(p_offset, p_size, local_x, local_y))
				return 1;
			// Path test is authoritative when available — skip triangle fallback
			return 0;
		}
	}

	size_t offset = ch->shape_offset;
	size_t count = ch->size;
	if (count < 3) return 0;

	// Inverse-transform test point into shape's local space
	double det = ma * md - mb * mc_m;
	if (det == 0.0) return 0;
	double inv_det = 1.0 / det;
	double sx = test_x - mtx;
	double sy = test_y - mty;
	double local_x = ( md * sx - mc_m * sy) * inv_det;
	double local_y = (-mb * sx + ma  * sy) * inv_det;

	// Count triangle hits separately for fills and strokes.
	// Stroke triangles (marked with bit 31 in column 2) use non-zero winding
	// because overlapping strokes at intersections should be unioned.
	// Fill triangles use even-odd winding (unless DefineShape4 nonzero flag).
	int fill_hits = 0;
	int stroke_hits = 0;
	size_t num_tris = count / 3;
	for (size_t t = 0; t < num_tris; t++) {
		const u32* v0 = shape_data[offset + t * 3 + 0];
		const u32* v1 = shape_data[offset + t * 3 + 1];
		const u32* v2 = shape_data[offset + t * 3 + 2];
		double ax = (double)*(const float*)&v0[0];
		double ay = (double)*(const float*)&v0[1];
		double bx = (double)*(const float*)&v1[0];
		double by = (double)*(const float*)&v1[1];
		double cx = (double)*(const float*)&v2[0];
		double cy = (double)*(const float*)&v2[1];

		if (pit(local_x, local_y, ax, ay, bx, by, cx, cy)) {
			if (v0[2] & 0x80000000)
				stroke_hits++;
			else
				fill_hits++;
		}
	}

	if (stroke_hits > 0) return 1;  // strokes always use non-zero (union)
	if (ng_uses_nonzero_winding(char_id))
		return fill_hits > 0;  // non-zero: any hit means inside
	return (fill_hits % 2) == 1;  // even-odd: odd count = inside
}
