#!/usr/bin/env python3
"""
Generate the Shift-JIS double-byte decode table for
SWFModernRuntime/src/utils.c.

AVM1's form loader (loadVariables / loadVariablesNum) has to decode legacy
byte payloads when System.useCodepage is true; one of the encodings the
detector can pick is Shift-JIS. Ruffle gets this from `encoding_rs`; we
generate the equivalent table here so the runtime stays dependency-free.

Layout is the WHATWG Encoding Standard's Shift_JIS pointer arithmetic:

    ptr = (lead - (lead < 0xA0 ? 0x81 : 0xC1)) * 188
        + (trail - (trail < 0x7F ? 0x40 : 0x41))
    cp  = sjis_index[ptr]           /* 0 == unmapped */

so the array is 11280 entries (60 lead slots x 188 trail slots).

The mappings come from CPython's `cp932` codec (Windows-31J), which is the
same family WHATWG's `index jis0208` is derived from: both take the Windows
readings for the six contested punctuation code points (0x8160 -> U+FF5E,
not U+301C, etc.), both carry the NEC/IBM extension rows, and cp932's
0xF040.. PUA block lands on exactly the U+E000 + (ptr - 8836) values
WHATWG's decoder computes algorithmically. Where they can still disagree is
a handful of cp932 duplicate IBM mappings; none are reachable from the
corpus, and Flash on Windows would have used the cp932 reading anyway.
Single bytes are not tabulated -- utils.c handles them algorithmically.

Usage:
    python3 scripts/generate_shift_jis_table.py          # rewrite utils.c in place
    python3 scripts/generate_shift_jis_table.py --stdout # print the block only

The emitted text replaces whatever sits between the

    /* BEGIN GENERATED shift_jis_index */
    /* END GENERATED shift_jis_index */

markers in SWFModernRuntime/src/utils.c. Everything outside the markers is
left untouched, so the script is safe to re-run.
"""

import os
import sys

BEGIN = "/* BEGIN GENERATED shift_jis_index */"
END = "/* END GENERATED shift_jis_index */"

TABLE_SIZE = 11280  # 60 * 188


def build_table():
    table = [0] * TABLE_SIZE
    mapped = 0
    leads = list(range(0x81, 0xA0)) + list(range(0xE0, 0xFD))
    for lead in leads:
        for trail in range(0x40, 0xFD):
            if trail == 0x7F:
                continue
            try:
                s = bytes([lead, trail]).decode("cp932")
            except UnicodeDecodeError:
                continue
            if len(s) != 1:
                continue
            cp = ord(s)
            if cp > 0xFFFF:
                continue
            ptr = (lead - (0x81 if lead < 0xA0 else 0xC1)) * 188 \
                + (trail - (0x40 if trail < 0x7F else 0x41))
            assert 0 <= ptr < TABLE_SIZE, (lead, trail, ptr)
            table[ptr] = cp
            mapped += 1
    return table, mapped


def emit(table, mapped):
    lines = []
    lines.append(BEGIN)
    lines.append("/* Shift-JIS (Windows-31J / cp932) double-byte table, generated by")
    lines.append(" * scripts/generate_shift_jis_table.py. Indexed by the WHATWG")
    lines.append(" * Shift_JIS pointer; %d mappings, 0 means unmapped (U+FFFD)." % mapped)
    lines.append(" * Do not hand-edit. */")
    lines.append("static const uint16_t sjis_index[%d] = {" % TABLE_SIZE)
    per_line = 12
    for i in range(0, TABLE_SIZE, per_line):
        chunk = table[i:i + per_line]
        lines.append("\t" + ",".join("0x%04X" % c for c in chunk) + ",")
    lines.append("};")
    lines.append(END)
    return "\n".join(lines) + "\n"


def main():
    table, mapped = build_table()

    # The three code points the corpus actually grades (form_loader_encoding_3).
    checks = {(0x95, 0xD0): 0x7247, (0x89, 0xBC): 0x4EEE, (0x96, 0xBC): 0x540D}
    for (lead, trail), want in checks.items():
        ptr = (lead - (0x81 if lead < 0xA0 else 0xC1)) * 188 \
            + (trail - (0x40 if trail < 0x7F else 0x41))
        got = table[ptr]
        if got != want:
            print("ERROR: %02X %02X -> U+%04X, expected U+%04X"
                  % (lead, trail, got, want), file=sys.stderr)
            sys.exit(1)

    block = emit(table, mapped)

    if "--stdout" in sys.argv:
        sys.stdout.write(block)
        return

    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target = os.path.join(base, "SWFModernRuntime", "src", "utils.c")
    with open(target, "r", encoding="utf-8") as f:
        src = f.read()

    if BEGIN not in src or END not in src:
        print("ERROR: markers not found in %s" % target, file=sys.stderr)
        sys.exit(1)

    head = src[:src.index(BEGIN)]
    tail = src[src.index(END) + len(END):]
    tail = tail.lstrip("\n")
    with open(target, "w", encoding="utf-8") as f:
        f.write(head + block + "\n" + tail)

    print("Wrote %d mappings (%d entries) to %s" % (mapped, TABLE_SIZE, target))


if __name__ == "__main__":
    main()
